-- Combined Statcast table for MLB_ALL_TIME + Statcast_2024 (adds bat_speed, swing_length)

CREATE TABLE IF NOT EXISTS public.pitches_statcast (
  pitch_type                               text,
  game_date                                date,
  release_speed                            double precision,
  release_pos_x                            double precision,
  release_pos_z                            double precision,
  player_name                              text,
  batter                                   integer,
  pitcher                                  integer,
  events                                   text,
  description                              text,
  spin_dir                                 double precision,
  spin_rate_deprecated                     double precision,
  break_angle_deprecated                   double precision,
  break_length_deprecated                  double precision,
  zone                                     smallint,
  des                                      text,
  game_type                                text,
  stand                                    text,
  p_throws                                 text,
  home_team                                text,
  away_team                                text,
  "type"                                   text,
  hit_location                             smallint,
  bb_type                                  text,
  balls                                    smallint,
  strikes                                  smallint,
  game_year                                integer,
  pfx_x                                    double precision,
  pfx_z                                    double precision,
  plate_x                                  double precision,
  plate_z                                  double precision,
  on_3b                                    integer,
  on_2b                                    integer,
  on_1b                                    integer,
  outs_when_up                             smallint,
  inning                                   smallint,
  inning_topbot                            text,
  hc_x                                     double precision,
  hc_y                                     double precision,
  tfs_deprecated                           text,
  tfs_zulu_deprecated                      text,
  fielder_2                                integer,
  umpire                                   text,
  sv_id                                    text,
  vx0                                      double precision,
  vy0                                      double precision,
  vz0                                      double precision,
  ax                                       double precision,
  ay                                       double precision,
  az                                       double precision,
  sz_top                                   double precision,
  sz_bot                                   double precision,
  hit_distance_sc                          double precision,
  launch_speed                             double precision,
  launch_angle                             double precision,
  effective_speed                          double precision,
  release_spin_rate                        double precision,
  release_extension                        double precision,
  game_pk                                  integer,
  "pitcher.1"                              integer,
  "fielder_2.1"                            integer,
  fielder_3                                integer,
  fielder_4                                integer,
  fielder_5                                integer,
  fielder_6                                integer,
  fielder_7                                integer,
  fielder_8                                integer,
  fielder_9                                integer,
  release_pos_y                            double precision,
  estimated_ba_using_speedangle            double precision,
  estimated_woba_using_speedangle          double precision,
  woba_value                               double precision,
  woba_denom                               double precision,
  babip_value                              double precision,
  iso_value                                double precision,
  launch_speed_angle                       double precision,
  at_bat_number                            integer,
  pitch_number                             integer,
  pitch_name                               text,
  home_score                               integer,
  away_score                               integer,
  bat_score                                integer,
  fld_score                                integer,
  post_away_score                          integer,
  post_home_score                          integer,
  post_bat_score                           integer,
  post_fld_score                           integer,
  if_fielding_alignment                    text,
  of_fielding_alignment                    text,
  spin_axis                                double precision,
  delta_home_win_exp                       double precision,
  delta_run_exp                            double precision,
  -- extra features present only in Statcast_2024
  bat_speed                                double precision,
  swing_length                             double precision
);
