DROP TABLE IF EXISTS public.pitches_a;
CREATE TABLE IF NOT EXISTS public.pitches_a (
  -- 1–7: timing
  pitchno                integer,
  date                   date,
  "time"                 time without time zone,
  utcdate                date,
  utctime                time without time zone,
  localdatetime          timestamptz,
  utcdatetime            timestamptz,

  -- 8–17: counts / identities / teams
  paofinning             smallint,
  pitchofpa              smallint,
  pitcher                text,
  pitcherid              text,
  pitcherthrows          text,
  pitcherteam            text,
  batter                 text,
  batterid               text,
  batterside             text,
  batterteam             text,

  -- 18–23: game context
  pitcherset             text,
  inning                 smallint,
  top_bottom             text,
  outs                   smallint,
  balls                  smallint,
  strikes                smallint,

  -- 24–33: classifications & results
  taggedpitchtype        text,
  autopitchtype          text,
  pitchcall              text,
  korbb                  text,
  taggedhittype          text, 
  autohittype            text,
  playresult             text,
  outsonplay             smallint,
  runsscored             smallint,
  notes                  text,

  -- 34–55: pitch release & immediate flight
  relspeed               double precision,
  vertrelangle           double precision,
  horzrelangle           double precision,
  spinrate               double precision,
  spinaxis               double precision,
  tilt                   text,               -- TrackMan "clock" format like '3:00'
  relheight              double precision,
  relside                double precision,
  extension              double precision,
  vertbreak              double precision,
  inducedvertbreak       double precision,
  horzbreak              double precision,
  platelocheight         double precision,
  platelocside           double precision,
  zonespeed              double precision,
  vertapprangle          double precision,
  horzapprangle          double precision,
  zonetime               double precision,
  exitspeed              double precision,
  angle                  double precision,
  direction              double precision,
  hitspinrate            double precision,

  -- 56–62: batted-ball trajectory summary
  positionat110x         double precision,
  positionat110y         double precision,
  positionat110z         double precision,
  distance               double precision,
  lasttrackeddistance    double precision,
  bearing                double precision,
  hangtime               double precision,

  -- 63–73: movement & initial state
  pfxx                   double precision,
  pfxz                   double precision,
  x0                     double precision,
  y0                     double precision,
  z0                     double precision,
  vx0                    double precision,
  vy0                    double precision,
  vz0                    double precision,
  ax0                    double precision,
  ay0                    double precision,
  az0                    double precision,

  -- 74–83: teams/venue/league IDs
  hometeam               text,
  awayteam               text,
  stadium                text,
  level                  text,
  league                 text,
  gameid                 text,
  pitchuid               text,
  "system"               text,
  hometeamforeignid      text,
  awayteamforeignid      text,
  gameforeignid          text,

  -- 85–90: catcher & play identifiers
  catcher                text,
  catcherid              text,
  catcherthrows          text,
  catcherteam            text,
  gameuid                text,
  playid                 text,

  -- 91–97: derived speeds/heights & last measured
  effectivevelo          double precision,
  maxheight              double precision,
  measuredduration       double precision,
  speeddrop              double precision,
  pitchlastmeasuredx     double precision,
  pitchlastmeasuredy     double precision,
  pitchlastmeasuredz     double precision,

  -- 98–106: pitch trajectory polynomial coeffs
  pitchtrajectoryxc0     double precision,
  pitchtrajectoryxc1     double precision,
  pitchtrajectoryxc2     double precision,
  pitchtrajectoryyc0     double precision,
  pitchtrajectoryyc1     double precision,
  pitchtrajectoryyc2     double precision,
  pitchtrajectoryzc0     double precision,
  pitchtrajectoryzc1     double precision,
  pitchtrajectoryzc2     double precision,

  contactpositionx       double precision,
  contactpositiony       double precision,
  contactpositionz       double precision,

  -- 107–134: hit spin & trajectory coeffs
  hitspinaxis            double precision,
  hittrajectoryxc0       double precision,
  hittrajectoryxc1       double precision,
  hittrajectoryxc2       double precision,
  hittrajectoryxc3       double precision,
  hittrajectoryxc4       double precision,
  hittrajectoryxc5       double precision,
  hittrajectoryxc6       double precision,
  hittrajectoryxc7       double precision,
  hittrajectoryxc8       double precision,
  hittrajectoryyc0       double precision,
  hittrajectoryyc1       double precision,
  hittrajectoryyc2       double precision,
  hittrajectoryyc3       double precision,
  hittrajectoryyc4       double precision,
  hittrajectoryyc5       double precision,
  hittrajectoryyc6       double precision,
  hittrajectoryyc7       double precision,
  hittrajectoryyc8       double precision,
  hittrajectoryzc0       double precision,
  hittrajectoryzc1       double precision,
  hittrajectoryzc2       double precision,
  hittrajectoryzc3       double precision,
  hittrajectoryzc4       double precision,
  hittrajectoryzc5       double precision,
  hittrajectoryzc6       double precision,
  hittrajectoryzc7       double precision,
  hittrajectoryzc8       double precision,

  -- 135–156: catcher throw kinematics & coeffs
  throwspeed             double precision,
  poptime                double precision,
  exchangetime           double precision,
  timetobase             double precision,
  catchpositionx         double precision,
  catchpositiony         double precision,
  catchpositionz         double precision,
  throwpositionx         double precision,
  throwpositiony         double precision,
  throwpositionz         double precision,
  basepositionx          double precision,
  basepositiony          double precision,
  basepositionz          double precision,
  throwtrajectoryxc0     double precision,
  throwtrajectoryxc1     double precision,
  throwtrajectoryxc2     double precision,
  throwtrajectoryyc0     double precision,
  throwtrajectoryyc1     double precision,
  throwtrajectoryyc2     double precision,
  throwtrajectoryzc0     double precision,
  throwtrajectoryzc1     double precision,
  throwtrajectoryzc2     double precision,

  -- 157–167: data quality/confidence flags
  pitchreleaseconfidence         text,
  pitchlocationconfidence        text,
  pitchmovementconfidence        text,
  hitlaunchconfidence            text,
  hitlandingconfidence           text,
  catcherthrowcatchconfidence    text,
  catcherthrowreleaseconfidence  text,
  catcherthrowlocationconfidence text

);

-- Optional: owner/privileges (adjust as needed)
-- ALTER TABLE public.pitches_a OWNER TO micro;
-- GRANT SELECT ON public.pitches_a TO readonly;

