-- load_pitches_a_from_staging.sql
-- Normalizes stg.pitches_fmt_a -> public.pitches_a with ALL 167 columns.

BEGIN;

-- 1) Normalization view (all casts/NULL handling done here)
CREATE OR REPLACE VIEW stg.v_pitches_a_norm AS
SELECT
  -- 1–7 timing
  NULLIF(pitchno,'')::integer                              AS pitchno,
  NULLIF("date",'')::date                                   AS "date",
  NULLIF("time",'')::time                                   AS "time",
  NULLIF(utcdate,'')::date                                  AS utcdate,
  NULLIF(utctime,'')::time                                  AS utctime,
  NULLIF(localdatetime,'')::timestamptz                     AS localdatetime,
  NULLIF(utcdatetime,'')::timestamptz                       AS utcdatetime,

  -- 8–17 identities/teams
  ROUND(NULLIF(paofinning,'')::numeric)::smallint AS paofinning,
  ROUND(NULLIF(pitchofpa,'')::numeric)::smallint AS pitchofpa,

 -- NULLIF(paofinning,'')::smallint                           AS paofinning,
 -- NULLIF(pitchofpa,'')::smallint                            AS pitchofpa,
  NULLIF(pitcher,'')                                        AS pitcher,
  NULLIF(pitcherid,'')                                      AS pitcherid,
  NULLIF(pitcherthrows,'')                                  AS pitcherthrows,
  NULLIF(pitcherteam,'')                                    AS pitcherteam,
  NULLIF(batter,'')                                         AS batter,
  NULLIF(batterid,'')                                       AS batterid,
  NULLIF(batterside,'')                                     AS batterside,
  NULLIF(batterteam,'')                                     AS batterteam,

  -- 18–23 game context
  NULLIF(pitcherset,'')                                     AS pitcherset,
  NULLIF(inning,'')::smallint                               AS inning,
  NULLIF(top_bottom,'')                                     AS top_bottom,
  NULLIF(outs,'')::smallint                                 AS outs,
  NULLIF(balls,'')::smallint                                AS balls,
  NULLIF(strikes,'')::smallint                              AS strikes,

  -- 24–33 classifications/results (includes AutoHitType per your reorder)
  NULLIF(taggedpitchtype,'')                                AS taggedpitchtype,
  NULLIF(autopitchtype,'')                                  AS autopitchtype,
  NULLIF(pitchcall,'')                                      AS pitchcall,
  NULLIF(korbb,'')                                          AS korbb,
  NULLIF(taggedhittype,'')                                  AS taggedhittype,
  NULLIF(autohittype,'')                                    AS autohittype,
  NULLIF(playresult,'')                                     AS playresult,
  NULLIF(outsonplay,'')::smallint                           AS outsonplay,
  NULLIF(runsscored,'')::smallint                           AS runsscored,
  NULLIF(notes,'')                                          AS notes,

  -- 34–55 pitch release/flight
  NULLIF(relspeed,'')::double precision                     AS relspeed,
  NULLIF(vertrelangle,'')::double precision                 AS vertrelangle,
  NULLIF(horzrelangle,'')::double precision                 AS horzrelangle,
  NULLIF(spinrate,'')::double precision                     AS spinrate,
  NULLIF(spinaxis,'')::double precision                     AS spinaxis,
  NULLIF(tilt,'')                                           AS tilt,
  NULLIF(relheight,'')::double precision                    AS relheight,
  NULLIF(relside,'')::double precision                      AS relside,
  NULLIF(extension,'')::double precision                     AS extension,
  NULLIF(vertbreak,'')::double precision                    AS vertbreak,
  NULLIF(inducedvertbreak,'')::double precision             AS inducedvertbreak,
  NULLIF(horzbreak,'')::double precision                    AS horzbreak,
  NULLIF(platelocheight,'')::double precision               AS platelocheight,
  NULLIF(platelocside,'')::double precision                 AS platelocside,
  NULLIF(zonespeed,'')::double precision                    AS zonespeed,
  NULLIF(vertapprangle,'')::double precision                AS vertapprangle,
  NULLIF(horzapprangle,'')::double precision                AS horzapprangle,
  NULLIF(zonetime,'')::double precision                     AS zonetime,
  NULLIF(exitspeed,'')::double precision                    AS exitspeed,
  NULLIF(angle,'')::double precision                        AS angle,
  NULLIF(direction,'')::double precision                    AS direction,
  NULLIF(hitspinrate,'')::double precision                  AS hitspinrate,

  -- 56–62 batted-ball trajectory summary
  NULLIF(positionat110x,'')::double precision               AS positionat110x,
  NULLIF(positionat110y,'')::double precision               AS positionat110y,
  NULLIF(positionat110z,'')::double precision               AS positionat110z,
  NULLIF(distance,'')::double precision                     AS distance,
  NULLIF(lasttrackeddistance,'')::double precision          AS lasttrackeddistance,
  NULLIF(bearing,'')::double precision                      AS bearing,
  NULLIF(hangtime,'')::double precision                     AS hangtime,

  -- 63–73 movement & initial state
  NULLIF(pfxx,'')::double precision                         AS pfxx,
  NULLIF(pfxz,'')::double precision                         AS pfxz,
  NULLIF(x0,'')::double precision                           AS x0,
  NULLIF(y0,'')::double precision                           AS y0,
  NULLIF(z0,'')::double precision                           AS z0,
  NULLIF(vx0,'')::double precision                          AS vx0,
  NULLIF(vy0,'')::double precision                          AS vy0,
  NULLIF(vz0,'')::double precision                          AS vz0,
  NULLIF(ax0,'')::double precision                          AS ax0,
  NULLIF(ay0,'')::double precision                          AS ay0,
  NULLIF(az0,'')::double precision                          AS az0,

  -- 74–90 teams/venue/ids
  NULLIF(hometeam,'')                                       AS hometeam,
  NULLIF(awayteam,'')                                       AS awayteam,
  NULLIF(stadium,'')                                        AS stadium,
  NULLIF(level,'')                                          AS level,
  NULLIF(league,'')                                         AS league,
  NULLIF(gameid,'')                                         AS gameid,
  NULLIF(pitchuid,'')                                       AS pitchuid,
  NULLIF("system",'')                                       AS "system",
  NULLIF(hometeamforeignid,'')                              AS hometeamforeignid,
  NULLIF(awayteamforeignid,'')                              AS awayteamforeignid,
  NULLIF(gameforeignid,'')                                  AS gameforeignid,
  NULLIF(catcher,'')                                        AS catcher,
  NULLIF(catcherid,'')                                      AS catcherid,
  NULLIF(catcherthrows,'')                                  AS catcherthrows,
  NULLIF(catcherteam,'')                                    AS catcherteam,
  NULLIF(gameuid,'')                                        AS gameuid,
  NULLIF(playid,'')                                         AS playid,

  -- 91–97 derived speeds/heights & last measured
  NULLIF(effectivevelo,'')::double precision                AS effectivevelo,
  NULLIF(maxheight,'')::double precision                    AS maxheight,
  NULLIF(measuredduration,'')::double precision             AS measuredduration,
  NULLIF(speeddrop,'')::double precision                    AS speeddrop,
  NULLIF(pitchlastmeasuredx,'')::double precision           AS pitchlastmeasuredx,
  NULLIF(pitchlastmeasuredy,'')::double precision           AS pitchlastmeasuredy,
  NULLIF(pitchlastmeasuredz,'')::double precision           AS pitchlastmeasuredz,

  -- 98–106 pitch trajectory polynomial coeffs
  NULLIF(pitchtrajectoryxc0,'')::double precision           AS pitchtrajectoryxc0,
  NULLIF(pitchtrajectoryxc1,'')::double precision           AS pitchtrajectoryxc1,
  NULLIF(pitchtrajectoryxc2,'')::double precision           AS pitchtrajectoryxc2,
  NULLIF(pitchtrajectoryyc0,'')::double precision           AS pitchtrajectoryyc0,
  NULLIF(pitchtrajectoryyc1,'')::double precision           AS pitchtrajectoryyc1,
  NULLIF(pitchtrajectoryyc2,'')::double precision           AS pitchtrajectoryyc2,
  NULLIF(pitchtrajectoryzc0,'')::double precision           AS pitchtrajectoryzc0,
  NULLIF(pitchtrajectoryzc1,'')::double precision           AS pitchtrajectoryzc1,
  NULLIF(pitchtrajectoryzc2,'')::double precision           AS pitchtrajectoryzc2,

  -- 107–134 bat contact & hit trajectory
  NULLIF(contactpositionx,'')::double precision             AS contactpositionx,
  NULLIF(contactpositiony,'')::double precision             AS contactpositiony,
  NULLIF(contactpositionz,'')::double precision             AS contactpositionz,
  NULLIF(hitspinaxis,'')::double precision                  AS hitspinaxis,
  NULLIF(hittrajectoryxc0,'')::double precision             AS hittrajectoryxc0,
  NULLIF(hittrajectoryxc1,'')::double precision             AS hittrajectoryxc1,
  NULLIF(hittrajectoryxc2,'')::double precision             AS hittrajectoryxc2,
  NULLIF(hittrajectoryxc3,'')::double precision             AS hittrajectoryxc3,
  NULLIF(hittrajectoryxc4,'')::double precision             AS hittrajectoryxc4,
  NULLIF(hittrajectoryxc5,'')::double precision             AS hittrajectoryxc5,
  NULLIF(hittrajectoryxc6,'')::double precision             AS hittrajectoryxc6,
  NULLIF(hittrajectoryxc7,'')::double precision             AS hittrajectoryxc7,
  NULLIF(hittrajectoryxc8,'')::double precision             AS hittrajectoryxc8,
  NULLIF(hittrajectoryyc0,'')::double precision             AS hittrajectoryyc0,
  NULLIF(hittrajectoryyc1,'')::double precision             AS hittrajectoryyc1,
  NULLIF(hittrajectoryyc2,'')::double precision             AS hittrajectoryyc2,
  NULLIF(hittrajectoryyc3,'')::double precision             AS hittrajectoryyc3,
  NULLIF(hittrajectoryyc4,'')::double precision             AS hittrajectoryyc4,
  NULLIF(hittrajectoryyc5,'')::double precision             AS hittrajectoryyc5,
  NULLIF(hittrajectoryyc6,'')::double precision             AS hittrajectoryyc6,
  NULLIF(hittrajectoryyc7,'')::double precision             AS hittrajectoryyc7,
  NULLIF(hittrajectoryyc8,'')::double precision             AS hittrajectoryyc8,
  NULLIF(hittrajectoryzc0,'')::double precision             AS hittrajectoryzc0,
  NULLIF(hittrajectoryzc1,'')::double precision             AS hittrajectoryzc1,
  NULLIF(hittrajectoryzc2,'')::double precision             AS hittrajectoryzc2,
  NULLIF(hittrajectoryzc3,'')::double precision             AS hittrajectoryzc3,
  NULLIF(hittrajectoryzc4,'')::double precision             AS hittrajectoryzc4,
  NULLIF(hittrajectoryzc5,'')::double precision             AS hittrajectoryzc5,
  NULLIF(hittrajectoryzc6,'')::double precision             AS hittrajectoryzc6,
  NULLIF(hittrajectoryzc7,'')::double precision             AS hittrajectoryzc7,
  NULLIF(hittrajectoryzc8,'')::double precision             AS hittrajectoryzc8,

  -- 135–156 catcher throw kinematics & coeffs
  NULLIF(throwspeed,'')::double precision                   AS throwspeed,
  NULLIF(poptime,'')::double precision                      AS poptime,
  NULLIF(exchangetime,'')::double precision                 AS exchangetime,
  NULLIF(timetobase,'')::double precision                   AS timetobase,
  NULLIF(catchpositionx,'')::double precision               AS catchpositionx,
  NULLIF(catchpositiony,'')::double precision               AS catchpositiony,
  NULLIF(catchpositionz,'')::double precision               AS catchpositionz,
  NULLIF(throwpositionx,'')::double precision               AS throwpositionx,
  NULLIF(throwpositiony,'')::double precision               AS throwpositiony,
  NULLIF(throwpositionz,'')::double precision               AS throwpositionz,
  NULLIF(basepositionx,'')::double precision                AS basepositionx,
  NULLIF(basepositiony,'')::double precision                AS basepositiony,
  NULLIF(basepositionz,'')::double precision                AS basepositionz,
  NULLIF(throwtrajectoryxc0,'')::double precision           AS throwtrajectoryxc0,
  NULLIF(throwtrajectoryxc1,'')::double precision           AS throwtrajectoryxc1,
  NULLIF(throwtrajectoryxc2,'')::double precision           AS throwtrajectoryxc2,
  NULLIF(throwtrajectoryyc0,'')::double precision           AS throwtrajectoryyc0,
  NULLIF(throwtrajectoryyc1,'')::double precision           AS throwtrajectoryyc1,
  NULLIF(throwtrajectoryyc2,'')::double precision           AS throwtrajectoryyc2,
  NULLIF(throwtrajectoryzc0,'')::double precision           AS throwtrajectoryzc0,
  NULLIF(throwtrajectoryzc1,'')::double precision           AS throwtrajectoryzc1,
  NULLIF(throwtrajectoryzc2,'')::double precision           AS throwtrajectoryzc2,

  -- 157–167 data quality/confidence
  NULLIF(pitchreleaseconfidence,'')                         AS pitchreleaseconfidence,
  NULLIF(pitchlocationconfidence,'')                        AS pitchlocationconfidence,
  NULLIF(pitchmovementconfidence,'')                        AS pitchmovementconfidence,
  NULLIF(hitlaunchconfidence,'')                            AS hitlaunchconfidence,
  NULLIF(hitlandingconfidence,'')                           AS hitlandingconfidence,
  NULLIF(catcherthrowcatchconfidence,'')                    AS catcherthrowcatchconfidence,
  NULLIF(catcherthrowreleaseconfidence,'')                  AS catcherthrowreleaseconfidence,
  NULLIF(catcherthrowlocationconfidence,'')                 AS catcherthrowlocationconfidence
FROM stg.pitches_fmt_a;

-- 2) Load into your final table using explicit column list (order-safe)
INSERT INTO public.pitches_a (
  pitchno, "date", "time", utcdate, utctime, localdatetime, utcdatetime,
  paofinning, pitchofpa, pitcher, pitcherid, pitcherthrows, pitcherteam,
  batter, batterid, batterside, batterteam, pitcherset, inning, top_bottom,
  outs, balls, strikes, taggedpitchtype, autopitchtype, pitchcall, korbb,
  taggedhittype, autohittype, playresult, outsonplay, runsscored, notes,
  relspeed, vertrelangle, horzrelangle, spinrate, spinaxis, tilt, relheight,
  relside, extension, vertbreak, inducedvertbreak, horzbreak, platelocheight,
  platelocside, zonespeed, vertapprangle, horzapprangle, zonetime, exitspeed,
  angle, direction, hitspinrate, positionat110x, positionat110y, positionat110z,
  distance, lasttrackeddistance, bearing, hangtime, pfxx, pfxz, x0, y0, z0, vx0,
  vy0, vz0, ax0, ay0, az0, hometeam, awayteam, stadium, level, league, gameid,
  pitchuid, "system", hometeamforeignid, awayteamforeignid, gameforeignid,
  catcher, catcherid, catcherthrows, catcherteam, gameuid, playid,
  effectivevelo, maxheight, measuredduration, speeddrop, pitchlastmeasuredx,
  pitchlastmeasuredy, pitchlastmeasuredz,
  pitchtrajectoryxc0, pitchtrajectoryxc1, pitchtrajectoryxc2,
  pitchtrajectoryyc0, pitchtrajectoryyc1, pitchtrajectoryyc2,
  pitchtrajectoryzc0, pitchtrajectoryzc1, pitchtrajectoryzc2,
  contactpositionx, contactpositiony, contactpositionz,
  hitspinaxis,
  hittrajectoryxc0, hittrajectoryxc1, hittrajectoryxc2, hittrajectoryxc3, hittrajectoryxc4,
  hittrajectoryxc5, hittrajectoryxc6, hittrajectoryxc7, hittrajectoryxc8,
  hittrajectoryyc0, hittrajectoryyc1, hittrajectoryyc2, hittrajectoryyc3, hittrajectoryyc4,
  hittrajectoryyc5, hittrajectoryyc6, hittrajectoryyc7, hittrajectoryyc8,
  hittrajectoryzc0, hittrajectoryzc1, hittrajectoryzc2, hittrajectoryzc3, hittrajectoryzc4,
  hittrajectoryzc5, hittrajectoryzc6, hittrajectoryzc7, hittrajectoryzc8,
  throwspeed, poptime, exchangetime, timetobase,
  catchpositionx, catchpositiony, catchpositionz,
  throwpositionx, throwpositiony, throwpositionz,
  basepositionx, basepositiony, basepositionz,
  throwtrajectoryxc0, throwtrajectoryxc1, throwtrajectoryxc2,
  throwtrajectoryyc0, throwtrajectoryyc1, throwtrajectoryyc2,
  throwtrajectoryzc0, throwtrajectoryzc1, throwtrajectoryzc2,
  pitchreleaseconfidence, pitchlocationconfidence, pitchmovementconfidence,
  hitlaunchconfidence, hitlandingconfidence,
  catcherthrowcatchconfidence, catcherthrowreleaseconfidence, catcherthrowlocationconfidence
)
SELECT
  pitchno, "date", "time", utcdate, utctime, localdatetime, utcdatetime,
  paofinning, pitchofpa, pitcher, pitcherid, pitcherthrows, pitcherteam,
  batter, batterid, batterside, batterteam, pitcherset, inning, top_bottom,
  outs, balls, strikes, taggedpitchtype, autopitchtype, pitchcall, korbb,
  taggedhittype, autohittype, playresult, outsonplay, runsscored, notes,
  relspeed, vertrelangle, horzrelangle, spinrate, spinaxis, tilt, relheight,
  relside, extension, vertbreak, inducedvertbreak, horzbreak, platelocheight,
  platelocside, zonespeed, vertapprangle, horzapprangle, zonetime, exitspeed,
  angle, direction, hitspinrate, positionat110x, positionat110y, positionat110z,
  distance, lasttrackeddistance, bearing, hangtime, pfxx, pfxz, x0, y0, z0, vx0,
  vy0, vz0, ax0, ay0, az0, hometeam, awayteam, stadium, level, league, gameid,
  pitchuid, "system", hometeamforeignid, awayteamforeignid, gameforeignid,
  catcher, catcherid, catcherthrows, catcherteam, gameuid, playid,
  effectivevelo, maxheight, measuredduration, speeddrop, pitchlastmeasuredx,
  pitchlastmeasuredy, pitchlastmeasuredz,
  pitchtrajectoryxc0, pitchtrajectoryxc1, pitchtrajectoryxc2,
  pitchtrajectoryyc0, pitchtrajectoryyc1, pitchtrajectoryyc2,
  pitchtrajectoryzc0, pitchtrajectoryzc1, pitchtrajectoryzc2,
  contactpositionx, contactpositiony, contactpositionz,
  hitspinaxis,
  hittrajectoryxc0, hittrajectoryxc1, hittrajectoryxc2, hittrajectoryxc3, hittrajectoryxc4,
  hittrajectoryxc5, hittrajectoryxc6, hittrajectoryxc7, hittrajectoryxc8,
  hittrajectoryyc0, hittrajectoryyc1, hittrajectoryyc2, hittrajectoryyc3, hittrajectoryyc4,
  hittrajectoryyc5, hittrajectoryyc6, hittrajectoryyc7, hittrajectoryyc8,
  hittrajectoryzc0, hittrajectoryzc1, hittrajectoryzc2, hittrajectoryzc3, hittrajectoryzc4,
  hittrajectoryzc5, hittrajectoryzc6, hittrajectoryzc7, hittrajectoryzc8,
  throwspeed, poptime, exchangetime, timetobase,
  catchpositionx, catchpositiony, catchpositionz,
  throwpositionx, throwpositiony, throwpositionz,
  basepositionx, basepositiony, basepositionz,
  throwtrajectoryxc0, throwtrajectoryxc1, throwtrajectoryxc2,
  throwtrajectoryyc0, throwtrajectoryyc1, throwtrajectoryyc2,
  throwtrajectoryzc0, throwtrajectoryzc1, throwtrajectoryzc2,
  pitchreleaseconfidence, pitchlocationconfidence, pitchmovementconfidence,
  hitlaunchconfidence, hitlandingconfidence,
  catcherthrowcatchconfidence, catcherthrowreleaseconfidence, catcherthrowlocationconfidence
FROM stg.v_pitches_a_norm;

COMMIT;

