-- load_pitches_statcast_from_staging.sql
-- Normalize and load both Statcast formats (B = MLB_ALL_TIME, C = Statcast_2024)
-- into public.pitches_statcast. All columns are included explicitly.

BEGIN;

-- =========================================
-- View: Format B (MLB_ALL_TIME) -> normalized columns
-- Note: bat_speed and swing_length do not exist in B; set to NULL.
-- =========================================
CREATE OR REPLACE VIEW stg.v_pitches_statcast_b_norm AS
SELECT
  NULLIF(pitch_type,'')                                           AS pitch_type,
  NULLIF(game_date,'')::date                                      AS game_date,
  NULLIF(release_speed,'')::double precision                      AS release_speed,
  NULLIF(release_pos_x,'')::double precision                      AS release_pos_x,
  NULLIF(release_pos_z,'')::double precision                      AS release_pos_z,
  NULLIF(player_name,'')                                          AS player_name,
  NULLIF(batter,'')::integer                                       AS batter,
  NULLIF(pitcher,'')::integer                                      AS pitcher,
  NULLIF(events,'')                                               AS events,
  NULLIF(description,'')                                          AS description,
  NULLIF(spin_dir,'')::double precision                           AS spin_dir,
  NULLIF(spin_rate_deprecated,'')::double precision               AS spin_rate_deprecated,
  NULLIF(break_angle_deprecated,'')::double precision             AS break_angle_deprecated,
  NULLIF(break_length_deprecated,'')::double precision            AS break_length_deprecated,
  NULLIF(zone,'')::smallint                                       AS zone,
  NULLIF(des,'')                                                  AS des,
  NULLIF(game_type,'')                                            AS game_type,
  NULLIF(stand,'')                                                AS stand,
  NULLIF(p_throws,'')                                             AS p_throws,
  NULLIF(home_team,'')                                            AS home_team,
  NULLIF(away_team,'')                                            AS away_team,
  NULLIF("type",'')                                               AS "type",
  NULLIF(hit_location,'')::smallint                               AS hit_location,
  NULLIF(bb_type,'')                                              AS bb_type,
  NULLIF(balls,'')::smallint                                      AS balls,
  NULLIF(strikes,'')::smallint                                    AS strikes,
  NULLIF(game_year,'')::integer                                   AS game_year,
  NULLIF(pfx_x,'')::double precision                              AS pfx_x,
  NULLIF(pfx_z,'')::double precision                              AS pfx_z,
  NULLIF(plate_x,'')::double precision                            AS plate_x,
  NULLIF(plate_z,'')::double precision                            AS plate_z,
  NULLIF(on_3b,'')::integer                                       AS on_3b,
  NULLIF(on_2b,'')::integer                                       AS on_2b,
  NULLIF(on_1b,'')::integer                                       AS on_1b,
  NULLIF(outs_when_up,'')::smallint                               AS outs_when_up,
  NULLIF(inning,'')::smallint                                     AS inning,
  NULLIF(inning_topbot,'')                                        AS inning_topbot,
  NULLIF(hc_x,'')::double precision                               AS hc_x,
  NULLIF(hc_y,'')::double precision                               AS hc_y,
  NULLIF(tfs_deprecated,'')                                       AS tfs_deprecated,
  NULLIF(tfs_zulu_deprecated,'')                                  AS tfs_zulu_deprecated,
  NULLIF(fielder_2,'')::integer                                   AS fielder_2,
  NULLIF(umpire,'')                                               AS umpire,
  NULLIF(sv_id,'')                                                AS sv_id,
  NULLIF(vx0,'')::double precision                                AS vx0,
  NULLIF(vy0,'')::double precision                                AS vy0,
  NULLIF(vz0,'')::double precision                                AS vz0,
  NULLIF(ax,'')::double precision                                 AS ax,
  NULLIF(ay,'')::double precision                                 AS ay,
  NULLIF(az,'')::double precision                                 AS az,
  NULLIF(sz_top,'')::double precision                             AS sz_top,
  NULLIF(sz_bot,'')::double precision                             AS sz_bot,
  NULLIF(hit_distance_sc,'')::double precision                    AS hit_distance_sc,
  NULLIF(launch_speed,'')::double precision                       AS launch_speed,
  NULLIF(launch_angle,'')::double precision                       AS launch_angle,
  NULLIF(effective_speed,'')::double precision                    AS effective_speed,
  NULLIF(release_spin_rate,'')::double precision                  AS release_spin_rate,
  NULLIF(release_extension,'')::double precision                  AS release_extension,
  NULLIF(game_pk,'')::integer                                     AS game_pk,
  NULLIF(pitcher_1,'')::integer                                   AS "pitcher.1",
  NULLIF(fielder_2_1,'')::integer                                 AS "fielder_2.1",
  NULLIF(fielder_3,'')::integer                                   AS fielder_3,
  NULLIF(fielder_4,'')::integer                                   AS fielder_4,
  NULLIF(fielder_5,'')::integer                                   AS fielder_5,
  NULLIF(fielder_6,'')::integer                                   AS fielder_6,
  NULLIF(fielder_7,'')::integer                                   AS fielder_7,
  NULLIF(fielder_8,'')::integer                                   AS fielder_8,
  NULLIF(fielder_9,'')::integer                                   AS fielder_9,
  NULLIF(release_pos_y,'')::double precision                      AS release_pos_y,
  NULLIF(estimated_ba_using_speedangle,'')::double precision      AS estimated_ba_using_speedangle,
  NULLIF(estimated_woba_using_speedangle,'')::double precision    AS estimated_woba_using_speedangle,
  NULLIF(woba_value,'')::double precision                         AS woba_value,
  NULLIF(woba_denom,'')::double precision                         AS woba_denom,
  NULLIF(babip_value,'')::double precision                        AS babip_value,
  NULLIF(iso_value,'')::double precision                          AS iso_value,
  NULLIF(launch_speed_angle,'')::double precision                 AS launch_speed_angle,
  NULLIF(at_bat_number,'')::integer                               AS at_bat_number,
  NULLIF(pitch_number,'')::integer                                AS pitch_number,
  NULLIF(pitch_name,'')                                           AS pitch_name,
  NULLIF(home_score,'')::integer                                  AS home_score,
  NULLIF(away_score,'')::integer                                  AS away_score,
  NULLIF(bat_score,'')::integer                                   AS bat_score,
  NULLIF(fld_score,'')::integer                                   AS fld_score,
  NULLIF(post_away_score,'')::integer                             AS post_away_score,
  NULLIF(post_home_score,'')::integer                             AS post_home_score,
  NULLIF(post_bat_score,'')::integer                              AS post_bat_score,
  NULLIF(post_fld_score,'')::integer                              AS post_fld_score,
  NULLIF(if_fielding_alignment,'')                                AS if_fielding_alignment,
  NULLIF(of_fielding_alignment,'')                                AS of_fielding_alignment,
  NULLIF(spin_axis,'')::double precision                          AS spin_axis,
  NULLIF(delta_home_win_exp,'')::double precision                 AS delta_home_win_exp,
  NULLIF(delta_run_exp,'')::double precision                      AS delta_run_exp,
  CAST(NULL AS double precision)                                  AS bat_speed,
  CAST(NULL AS double precision)                                  AS swing_length
FROM stg.pitches_fmt_b;

-- =========================================
-- View: Format C (Statcast_2024) -> normalized columns
-- Note: Statcast_2024 has two extra columns: bat_speed, swing_length.
-- There may also be a leading unnamed CSV column; it is ignored here.
-- =========================================
CREATE OR REPLACE VIEW stg.v_pitches_statcast_c_norm AS
SELECT
  NULLIF(pitch_type,'')                                           AS pitch_type,
  NULLIF(game_date,'')::date                                      AS game_date,
  NULLIF(release_speed,'')::double precision                      AS release_speed,
  NULLIF(release_pos_x,'')::double precision                      AS release_pos_x,
  NULLIF(release_pos_z,'')::double precision                      AS release_pos_z,
  NULLIF(player_name,'')                                          AS player_name,
  NULLIF(batter,'')::integer                                       AS batter,
  NULLIF(pitcher,'')::integer                                      AS pitcher,
  NULLIF(events,'')                                               AS events,
  NULLIF(description,'')                                          AS description,
  NULLIF(spin_dir,'')::double precision                           AS spin_dir,
  NULLIF(spin_rate_deprecated,'')::double precision               AS spin_rate_deprecated,
  NULLIF(break_angle_deprecated,'')::double precision             AS break_angle_deprecated,
  NULLIF(break_length_deprecated,'')::double precision            AS break_length_deprecated,
  NULLIF(zone,'')::smallint                                       AS zone,
  NULLIF(des,'')                                                  AS des,
  NULLIF(game_type,'')                                            AS game_type,
  NULLIF(stand,'')                                                AS stand,
  NULLIF(p_throws,'')                                             AS p_throws,
  NULLIF(home_team,'')                                            AS home_team,
  NULLIF(away_team,'')                                            AS away_team,
  NULLIF("type",'')                                               AS "type",
  NULLIF(hit_location,'')::smallint                               AS hit_location,
  NULLIF(bb_type,'')                                              AS bb_type,
  NULLIF(balls,'')::smallint                                      AS balls,
  NULLIF(strikes,'')::smallint                                    AS strikes,
  NULLIF(game_year,'')::integer                                   AS game_year,
  NULLIF(pfx_x,'')::double precision                              AS pfx_x,
  NULLIF(pfx_z,'')::double precision                              AS pfx_z,
  NULLIF(plate_x,'')::double precision                            AS plate_x,
  NULLIF(plate_z,'')::double precision                            AS plate_z,
  NULLIF(on_3b,'')::integer                                       AS on_3b,
  NULLIF(on_2b,'')::integer                                       AS on_2b,
  NULLIF(on_1b,'')::integer                                       AS on_1b,
  NULLIF(outs_when_up,'')::smallint                               AS outs_when_up,
  NULLIF(inning,'')::smallint                                     AS inning,
  NULLIF(inning_topbot,'')                                        AS inning_topbot,
  NULLIF(hc_x,'')::double precision                               AS hc_x,
  NULLIF(hc_y,'')::double precision                               AS hc_y,
  NULLIF(tfs_deprecated,'')                                       AS tfs_deprecated,
  NULLIF(tfs_zulu_deprecated,'')                                  AS tfs_zulu_deprecated,
  NULLIF(fielder_2,'')::integer                                   AS fielder_2,
  NULLIF(umpire,'')                                               AS umpire,
  NULLIF(sv_id,'')                                                AS sv_id,
  NULLIF(vx0,'')::double precision                                AS vx0,
  NULLIF(vy0,'')::double precision                                AS vy0,
  NULLIF(vz0,'')::double precision                                AS vz0,
  NULLIF(ax,'')::double precision                                 AS ax,
  NULLIF(ay,'')::double precision                                 AS ay,
  NULLIF(az,'')::double precision                                 AS az,
  NULLIF(sz_top,'')::double precision                             AS sz_top,
  NULLIF(sz_bot,'')::double precision                             AS sz_bot,
  NULLIF(hit_distance_sc,'')::double precision                    AS hit_distance_sc,
  NULLIF(launch_speed,'')::double precision                       AS launch_speed,
  NULLIF(launch_angle,'')::double precision                       AS launch_angle,
  NULLIF(effective_speed,'')::double precision                    AS effective_speed,
  NULLIF(release_spin_rate,'')::double precision                  AS release_spin_rate,
  NULLIF(release_extension,'')::double precision                  AS release_extension,
  NULLIF(game_pk,'')::integer                                     AS game_pk,
  NULLIF(pitcher_1,'')::integer                                   AS "pitcher.1",
  NULLIF(fielder_2_1,'')::integer                                 AS "fielder_2.1",
  NULLIF(fielder_3,'')::integer                                   AS fielder_3,
  NULLIF(fielder_4,'')::integer                                   AS fielder_4,
  NULLIF(fielder_5,'')::integer                                   AS fielder_5,
  NULLIF(fielder_6,'')::integer                                   AS fielder_6,
  NULLIF(fielder_7,'')::integer                                   AS fielder_7,
  NULLIF(fielder_8,'')::integer                                   AS fielder_8,
  NULLIF(fielder_9,'')::integer                                   AS fielder_9,
  NULLIF(release_pos_y,'')::double precision                      AS release_pos_y,
  NULLIF(estimated_ba_using_speedangle,'')::double precision      AS estimated_ba_using_speedangle,
  NULLIF(estimated_woba_using_speedangle,'')::double precision    AS estimated_woba_using_speedangle,
  NULLIF(woba_value,'')::double precision                         AS woba_value,
  NULLIF(woba_denom,'')::double precision                         AS woba_denom,
  NULLIF(babip_value,'')::double precision                        AS babip_value,
  NULLIF(iso_value,'')::double precision                          AS iso_value,
  NULLIF(launch_speed_angle,'')::double precision                 AS launch_speed_angle,
  NULLIF(at_bat_number,'')::integer                               AS at_bat_number,
  NULLIF(pitch_number,'')::integer                                AS pitch_number,
  NULLIF(pitch_name,'')                                           AS pitch_name,
  NULLIF(home_score,'')::integer                                  AS home_score,
  NULLIF(away_score,'')::integer                                  AS away_score,
  NULLIF(bat_score,'')::integer                                   AS bat_score,
  NULLIF(fld_score,'')::integer                                   AS fld_score,
  NULLIF(post_away_score,'')::integer                             AS post_away_score,
  NULLIF(post_home_score,'')::integer                             AS post_home_score,
  NULLIF(post_bat_score,'')::integer                              AS post_bat_score,
  NULLIF(post_fld_score,'')::integer                              AS post_fld_score,
  NULLIF(if_fielding_alignment,'')                                AS if_fielding_alignment,
  NULLIF(of_fielding_alignment,'')                                AS of_fielding_alignment,
  NULLIF(spin_axis,'')::double precision                          AS spin_axis,
  NULLIF(delta_home_win_exp,'')::double precision                 AS delta_home_win_exp,
  NULLIF(delta_run_exp,'')::double precision                      AS delta_run_exp,
  NULLIF(bat_speed,'')::double precision                          AS bat_speed,
  NULLIF(swing_length,'')::double precision                       AS swing_length
FROM stg.pitches_fmt_c;

-- =========================================
-- Load both views into the target table
-- =========================================
INSERT INTO public.pitches_statcast (
  pitch_type, game_date, release_speed, release_pos_x, release_pos_z, player_name, batter, pitcher,
  events, description, spin_dir, spin_rate_deprecated, break_angle_deprecated, break_length_deprecated,
  zone, des, game_type, stand, p_throws, home_team, away_team, "type", hit_location, bb_type,
  balls, strikes, game_year, pfx_x, pfx_z, plate_x, plate_z, on_3b, on_2b, on_1b, outs_when_up,
  inning, inning_topbot, hc_x, hc_y, tfs_deprecated, tfs_zulu_deprecated, fielder_2, umpire, sv_id,
  vx0, vy0, vz0, ax, ay, az, sz_top, sz_bot, hit_distance_sc, launch_speed, launch_angle,
  effective_speed, release_spin_rate, release_extension, game_pk, "pitcher.1", "fielder_2.1",
  fielder_3, fielder_4, fielder_5, fielder_6, fielder_7, fielder_8, fielder_9, release_pos_y,
  estimated_ba_using_speedangle, estimated_woba_using_speedangle, woba_value, woba_denom, babip_value,
  iso_value, launch_speed_angle, at_bat_number, pitch_number, pitch_name, home_score, away_score,
  bat_score, fld_score, post_away_score, post_home_score, post_bat_score, post_fld_score,
  if_fielding_alignment, of_fielding_alignment, spin_axis, delta_home_win_exp, delta_run_exp,
  bat_speed, swing_length
)
SELECT * FROM stg.v_pitches_statcast_b_norm
UNION ALL
SELECT * FROM stg.v_pitches_statcast_c_norm;

COMMIT;

